version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies for $LAMBDA_FOLDER..."
      - python -m pip install --upgrade pip setuptools wheel
      - mkdir -p package
      - pip install -r $CODEBUILD_SRC_DIR/$LAMBDA_FOLDER/requirements.txt -t package/

  build:
    commands:
      - echo "Packaging Lambda function from $LAMBDA_FOLDER..."
      - cp $CODEBUILD_SRC_DIR/$LAMBDA_FOLDER/lambda_function.py package/
      - cd package
      - zip -r ../lambda_package.zip .
      - cd ..
      - echo "Build artifact ready:"
      - ls -l

artifacts:
  files:
    - lambda_package.zip
