version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - python -m pip install --upgrade pip setuptools wheel
      - mkdir -p build/dependencies
      - pip install -r $CODEBUILD_SRC_DIR/BusinessRuleExtractorSmallCodes/requirements.txt -t build/dependencies

  build:
    commands:
      - echo "Packaging Lambda function..."
      - mkdir -p build/code
      - cp $CODEBUILD_SRC_DIR/BusinessRuleExtractorSmallCodes/lambda_function.py build/code/
      - cp -r build/dependencies/* build/code/
      - cd build/code
      - zip -r ../../lambda_package.zip .
      - cd ../..
      - echo "ZIP contents:"
      - unzip -l lambda_package.zip
      - echo "Validating zip structure..."
      - unzip -l lambda_package.zip | awk '{print \$4}' | grep -qx 'lambda_function.py' || (echo "ERROR: lambda_function.py is NOT at root" && exit 1)
      - echo "lambda_function.py is at root"

artifacts:
  files:
    - lambda_package.zip
