version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "--- DEBUG START: Current directory listing ---"
      - ls -F
      - echo "--- DEBUG: Recursive source directory listing ---"
      - ls -RF $CODEBUILD_SRC_DIR/
      - echo "--- DEBUG END ---"
      - echo "Installing dependencies for BusinessRuleExtractorSmallCodes..."
      - python -m pip install --upgrade pip setuptools wheel
      - mkdir -p build/dependencies
      - pip install -r $CODEBUILD_SRC_DIR/BusinessRuleExtractorSmallCodes/requirements.txt -t build/dependencies

  build:
    commands:
      - echo "Packaging Lambda function..."
      - mkdir -p build/code
      - echo "--- DEBUG: Verifying lambda_function.py path ---"
      - if [ -f $CODEBUILD_SRC_DIR/BusinessRuleExtractorSmallCodes/lambda_function.py ]; then echo "SUCCESS: lambda_function.py found."; else echo "FAILURE: lambda_function.py NOT found. Exiting."; exit 1; fi
      - echo "--- DEBUG END ---"
      - cp $CODEBUILD_SRC_DIR/BusinessRuleExtractorSmallCodes/lambda_function.py build/code/
      - cp -r build/dependencies/* build/code/
      - cd build/code
      - zip -r ../../lambda_package.zip .
      - cd ../..
      - echo "ZIP contents:"
      - unzip -l lambda_package.zip
      - echo "Validation complete: lambda_function.py should be at root of zip."

artifacts:
  files:
    - lambda_package.zip
