version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies for $LAMBDA_FOLDER..."
      - python -m pip install --upgrade pip setuptools wheel
      - mkdir -p build/dependencies
      - pip install -r $CODEBUILD_SRC_DIR/$LAMBDA_FOLDER/requirements.txt -t build/dependencies

  build:
    commands:
      - echo "Packaging Lambda function from $LAMBDA_FOLDER..."
      - mkdir -p build/code
      - cp $CODEBUILD_SRC_DIR/$LAMBDA_FOLDER/*.py build/code/
      - cp -r build/dependencies/* build/code/
      - cd build/code
      - zip -r ../../lambda_package.zip .
      - cd ../..
      - echo "ZIP contents:"
      - unzip -l lambda_package.zip

artifacts:
  files:
    - lambda_package.zip
