version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies for BusinessRuleExtractorSmallCodes..."
      - python -m pip install --upgrade pip setuptools wheel
      - mkdir -p build/dependencies
      - pip install -r $CODEBUILD_SRC_DIR/BusinessRuleExtractorSmallCodes/requirements.txt -t build/dependencies

  build:
    commands:
      - echo "Packaging Lambda function from BusinessRuleExtractorSmallCodes..."
      - mkdir -p build/code
      - cp $CODEBUILD_SRC_DIR/BusinessRuleExtractorSmallCodes/lambda_function.py build/code/
      - cp -r build/dependencies/* build/code/
      - cd build/code
      - zip -r ../../lambda_package.zip .
      - cd ../..
      - echo "ZIP contents:"
      - unzip -l lambda_package.zip

artifacts:
  files:
    - lambda_package.zip
