version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package/
  build:
    commands:
      - echo "Packaging Lambda function..."
      - cp -r lambda_function.py package/
      - cd package
      - zip -r ../lambda_package.zip .
artifacts:
  files:
    - lambda_package.zip
