version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Upgrading pip and setuptools..."
      - python -m pip install --upgrade pip setuptools wheel
      - echo "Installing dependencies..."
      - ls -l   # Debug: confirm requirements.txt exists
      - mkdir -p package
      - pip install -r requirements.txt -t package/
  build:
    commands:
      - echo "Packaging Lambda function..."
      - cp lambda_function.py package/
      - cd package
      - zip -r ../lambda_package.zip .
      - cd ..
      - ls -l   # Debug: confirm lambda_package.zip exists

artifacts:
  files:
    - lambda_package.zip
